### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by nclavaud** [zlikavac32/php-measuring-units#1]
Hi :wave: 

Thank you so much for this great library.

How about making it compatible with PHP 8?

I first thought it would be as easy as allowing `^7.4||8.0` in `composer.json`, but it references `php-enum 3.0` and the latter only supports PHP 7.4.

I noticed that `php-enum dev-master` already supports PHP 8.0, though (and dropped support for PHP 7.4).

I could provide some help if needed, but I guess there should be a new release of `php-enum` before anything else.

**Comment by zlikavac32** [comment]
@nclavaud Hi, thank you for taking interest in this library.

Yes, I must release new version of my enum library and provide support for PHP 8.0 in this library. 

I'll do my best to do it this week :)

**Comment by nclavaud** [comment]
This is awesome, thank you a lot! :raised_hands:
